### ISSUE TITLE
Set Working Directory Lesson 

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-DataSkills-Lesson-Development#10]
@lwasser  This lesson is ready for edits (PR https://github.com/NEONInc/NEON-DataSkills-Lesson-Development/pull/9) 

It will not build correctly as the download data _include file is not currently in this repo.

**Comment by lwasser** [comment]
great - please add all of the includes to your PR. sound good?
thank you!

**Comment by lwasser** [comment]
i've assigned the PR to you to edit the lesson. let me know if you have any questions.

**Comment by mjones01** [comment]
I'm closing this comment as our discussion of the lesson is now on the Pull Request #9 and other issues for specific details the need changing.
